apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
specs:
  replicas: 1
  selector: 
    matchLabels: 
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    specs:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: secret 
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            ConfigMapKeyRef:
              name: mongo-config
              key: mongo-url

---
apiVersion: apps/v1
kind: Service
metadata:
  name: webapp-deployment
spec: 
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27107
      nodePort: 30200